### ISSUE TITLE
QuickSearch not actually searching

### ISSUE THREAD

**Issue by trillex** [felixkmh/QuickSearch-for-Playnite#24]
Having used your plugin before Playnite 9 without any issues, I installed it (and removed the old one) but have been simply unable to search anything. Everything is fully updated, Playnite 9.4 and QuickSearch 2.11.1.

The search is blank, it barely actually seems to be "loading" the searches when typing it out. 

There is nothing in the extensions.log during these searches, nor anything that is related to QuickSearch. 

I have tried to change all the settings, from on and off to one end of the slider to the other. Nothing had any sort of effect. I have also tried a few different themes with nothing to show for it. 

Best way I could show it was with a short video: https://i.imgur.com/eBFU3Sb.mp4

I have been with Playnite since the very start and after this update, I am afraid I might have to start from scratch, due to some strange issues like this. I'd really rather not, if it can be avoided. :) 

Let me know if I can give you other information.

**Comment by trillex** [comment]
No, nothing at all - at least not during the search. 

grepping for "null" or generally quicksearch in both logs provide no errors. 

I have completely removed both add-on as well as data/configuration files with the same results. 

Video where I tail both logs while attempting a search: https://i.imgur.com/UOLJWZF.mp4

**Comment by felixkmh** [comment]
Try using this debug build: [felixkmh_QuickSearch_Plugin_2_11_1.zip](https://github.com/felixkmh/QuickSearch-for-Playnite/files/7358359/felixkmh_QuickSearch_Plugin_2_11_1.zip). 
I added code to catch some errors that should be logged in the extensions.log file. Please check and report if it logs anything.

**Comment by trillex** [comment]
This error pops up every time I type in a new character, exact same one. 

`17-10 01:16:04.842|DEBUG|QuickSearch#SearchPlugin:Could not create SearchItems.
System.ArgumentException: Invalid Unicode code point found at index 2.
Parameter name: strInput
   at System.Text.Normalization.Normalize(String strInput, NormalizationForm normForm)
   at System.String.Normalize(NormalizationForm normalizationForm)
   at QuickSearch.Matching.RemoveDiacritics(String& text) in D:\Programmierung\playnite-dev\QuickSearch\source\Matching.cs:line 252
   at QuickSearch.Matching.MatchingLetterPairs2(String& str1, String& str2, ScoreNormalization normalization) in D:\Programmierung\playnite-dev\QuickSearch\source\Matching.cs:line 169
   at QuickSearch.SearchWindow.<>c__DisplayClass29_0.<ComputePreliminaryScore>b__1(ISearchKey`1 k) in D:\Programmierung\playnite-dev\QuickSearch\source\Views\SearchWindow.xaml.cs:line 215
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at QuickSearch.SearchWindow.ComputePreliminaryScore(ISearchItem`1 item, String input) in D:\Programmierung\playnite-dev\QuickSearch\source\Views\SearchWindow.xaml.cs:line 216
   at QuickSearch.SearchWindow.<>c__DisplayClass32_0.<QueueSearch>b__9(ISearchItem`1 item) in D:\Programmierung\playnite-dev\QuickSearch\source\Views\SearchWindow.xaml.cs:line 331
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()`

**Comment by felixkmh** [comment]
Okay, we are getting somewhere. Try running this:
[felixkmh_QuickSearch_Plugin_2_11_1.zip](https://github.com/felixkmh/QuickSearch-for-Playnite/files/7358623/felixkmh_QuickSearch_Plugin_2_11_1.zip).
There is some invalid Unicode in some string QuickSearch is trying to evaluate. This build should give you a hint in the log on which game and string that is. If it is a game name, try renaming it by typing out its name again.

**Comment by trillex** [comment]
Caught it!

```
17-10 11:26:02.527|DEBUG|QuickSearch#SearchPlugin:T�D contains invalid Unicode
System.ArgumentException: Invalid Unicode code point found at index 2.
Parameter name: strInput
   at System.Text.Normalization.Normalize(String strInput, NormalizationForm normForm)
   at System.String.Normalize(NormalizationForm normalizationForm)
   at QuickSearch.Matching.RemoveDiacritics(String& text) in D:\Programmierung\playnite-dev\QuickSearch\source\Matching.cs:line 255
17-10 11:26:02.527|DEBUG|QuickSearch#SearchPlugin:Encountered invalid Unicode when scoring "TOSS!🍌 Demo (T�D)"
System.ArgumentException: Invalid Unicode code point found at index 2.
Parameter name: strInput
   at QuickSearch.Matching.RemoveDiacritics(String& text) in D:\Programmierung\playnite-dev\QuickSearch\source\Matching.cs:line 270
   at QuickSearch.Matching.MatchingLetterPairs2(String& str1, String& str2, ScoreNormalization normalization) in D:\Programmierung\playnite-dev\QuickSearch\source\Matching.cs:line 169
   at QuickSearch.SearchWindow.<>c__DisplayClass29_0.<ComputePreliminaryScore>b__1(ISearchKey`1 k) in D:\Programmierung\playnite-dev\QuickSearch\source\Views\SearchWindow.xaml.cs:line 215
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at QuickSearch.SearchWindow.ComputePreliminaryScore(ISearchItem`1 item, String input) in D:\Programmierung\playnite-dev\QuickSearch\source\Views\SearchWindow.xaml.cs:line 216
   at QuickSearch.SearchWindow.<>c__DisplayClass32_0.<QueueSearch>b__8(ISearchItem`1 item) in D:\Programmierung\playnite-dev\QuickSearch\source\Views\SearchWindow.xaml.cs:line 332
```

So it was TOSS!🍌 Demo all along. Them unicode emotes. Removing it and QuickSearch works straight away. 

Someone thought themselves quite clever in this game: 

![image](https://user-images.githubusercontent.com/6444691/137621166-b1e88ec9-3dfc-411f-a678-18be5f272efe.png)

**Comment by felixkmh** [comment]
Great, now that I can work with. I should be able to fix that, even if names contain emotes.
The acronym appended to the game name is acutally not supposed to be there (along with the time and number of passes in the search bar). It is only there in for the purpose of debugging in debug builds, not in release builds.
