### ISSUE TITLE
[Bug] Search popup hotkeys not working

### ISSUE THREAD

**Issue by BloodShed-Oni** [felixkmh/QuickSearch-for-Playnite#58]
Hotkeys (local and global) for the search popup is not working (Changed, disable and re-enable them)

The only error I could find in the logs is this part in the playnite.log

```
01-07 17:42:19.530|ERROR|ExtensionFactory:Failed to execute OnApplicationStarted method from QuickSearch plugin.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at QuickSearch.SearchItems.ExtensionItemSource..ctor(SearchPlugin searchPlugin) in E:\Programmierung\playnite-dev\QuickSearch\source\SearchItems\ExtensionItemSource.cs:line 65
   at QuickSearch.SearchPlugin.OnApplicationStarted(OnApplicationStartedEventArgs args) in E:\Programmierung\playnite-dev\QuickSearch\source\SearchPlugin.cs:line 324
   at Playnite.Plugins.ExtensionFactory.NotifiyOnApplicationStarted() in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 710
```

**Comment by felixkmh** [comment]
fixed via 1580cbeecdf170eb9b3aafd29bdf853b4f893480
