### ISSUE TITLE
[Bug] QuickSearch can't load, when Sharenite enabled

### ISSUE THREAD

**Issue by XenorPLxx** [felixkmh/QuickSearch-for-Playnite#61]
When running QuickSearch alongside Searchnite plugin, QuickSearch doesn't load.

Here's what's in `playnite.log`:
```
05-09 12:02:19.629|ERROR|ExtensionFactory:Failed to execute OnApplicationStarted method from QuickSearch plugin.
System.NullReferenceException: Object reference not set to an instance of an object.
   at QuickSearch.SearchItems.ExtensionItemSource..ctor(SearchPlugin searchPlugin) in E:\Programmierung\playnite-dev\QuickSearch\source\SearchItems\ExtensionItemSource.cs:line 93
   at QuickSearch.SearchPlugin.OnApplicationStarted(OnApplicationStartedEventArgs args) in E:\Programmierung\playnite-dev\QuickSearch\source\SearchPlugin.cs:line 324
   at Playnite.Plugins.ExtensionFactory.NotifiyOnApplicationStarted() in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 710
```

Seems to be pointing at function that get main menu items, and Sharenite is creating one here https://github.com/sharenite/playnite-sharenite/blob/64e95fb0df18aa525482533a6b2244fa56c4b6cd/Sharenite.cs#L46.

**Comment by felixkmh** [comment]
Fixed in v2.24.3
