### ISSUE TITLE
Crash on Playnite 9 Beta 2

### ISSUE THREAD

**Issue by savvasdalkitsis** [felixkmh/QuickSearch-for-Playnite#8]
I get this while I try to launch the search dialog with both the global and local hot key:

```
System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception. ---> System.OverflowException: The image data generated an overflow during processing. ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(BitmapFrame frame, BitmapSourceSafeMILHandle wicSource, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapPalette palette)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapFrameDecode..ctor(Int32 frameNumber, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapDecoder decoder)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Windows.Baml2006.TypeConverterMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadDeferredContent(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings parentSettings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.DeferredResourceReference.GetValue(BaseValueSourceInternal valueSource)
   at System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   at System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Controls.Border.get_Background()
   at System.Windows.Controls.Border.OnRender(DrawingContext dc)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   at System.Windows.Media.VisualBrush.OnLayoutUpdated(Object sender, EventArgs args)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at QuickSearch.SearchPlugin.ToggleSearch() in D:\Programmierung\playnite-dev\QuickSearch\source\SearchPlugin.cs:line 453
   at QuickSearch.SearchPlugin.GlobalHotkeyCallback(IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in D:\Programmierung\playnite-dev\QuickSearch\source\SearchPlugin.cs:line 184
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 61
```

**Comment by felixkmh** [comment]
Is this happening regardless of whether the glass effect is enabled or disabled? And which the are you using?

**Comment by felixkmh** [comment]
It looks like the error in the log appeared while using the global hotkey while the Playnite window was not in focus. What does the error look like when using the local hotkey while the Playnite window is active and in focus? And can you provide the config.json of your QuickSearch installation?

**Comment by savvasdalkitsis** [comment]
I am getting the same crash when disabling the glass effect and while the playnite window is in focus:

```
10-09 12:41:55.315|ERROR|PlayniteApplication:Unhandled exception occured.
System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception. ---> System.OverflowException: The image data generated an overflow during processing. ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(BitmapFrame frame, BitmapSourceSafeMILHandle wicSource, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapPalette palette)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapFrameDecode..ctor(Int32 frameNumber, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapDecoder decoder)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Windows.Baml2006.TypeConverterMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadDeferredContent(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings parentSettings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.DeferredResourceReference.GetValue(BaseValueSourceInternal valueSource)
   at System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   at System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Controls.Border.get_Background()
   at System.Windows.Controls.Border.OnRender(DrawingContext dc)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Controls.Grid.ArrangeOverride(Size arrangeSize)
   at System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   at System.Windows.Media.VisualBrush.OnLayoutUpdated(Object sender, EventArgs args)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Controls.Primitives.Popup.SetRootVisualToPopupRoot()
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean asyncCall)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at QuickSearch.SearchPlugin.ToggleSearch() in D:\Programmierung\playnite-dev\QuickSearch\source\SearchPlugin.cs:line 368
   at QuickSearch.SearchPlugin.ActionCommand.Execute(Object parameter) in D:\Programmierung\playnite-dev\QuickSearch\source\SearchPlugin.cs:line 131
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in E:\Devel\Playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 61
```

Also, this is my config.json:

```
{
  "SearchShortcut": {
    "Key": 49,
    "Modifiers": 2
  },
  "SearchShortcutGlobal": {
    "Key": 49,
    "Modifiers": 3
  },
  "HotkeyText": "Control + F",
  "HotkeyTextGlobal": "Alt, Control + F",
  "Threshold": 0.55,
  "ExpandAllItems": true,
  "ShowSeperator": false,
  "IncrementalUpdate": true,
  "MaxNumberResults": 20,
  "EnableExternalGameActions": true,
  "EnableExternalItems": true,
  "AsyncItemsDelay": 500,
  "EnabledAssemblies": {
    "DuplicateHider": {
      "Items": true,
      "Actions": true
    },
    "QuickSearch": {
      "Items": true,
      "Actions": true
    }
  },
  "PrioritizationThreshold": 0.55,
  "MaxPrioritizedGames": 1,
  "InstallationStatusFirst": true,
  "ITADThreshold": 0.75,
  "ITADOverride": "+",
  "ITADEnabled": true,
  "EnabledITADShops": {
    "allyouplay": {
      "Name": "AllYouPlay",
      "Enabled": false
    },
    "amazonus": {
      "Name": "Amazon",
      "Enabled": true
    },
    "battlenet": {
      "Name": "Blizzard",
      "Enabled": true
    },
    "bundlestars": {
      "Name": "Fanatical",
      "Enabled": true
    },
    "direct2drive": {
      "Name": "Direct2Drive",
      "Enabled": true
    },
    "dlgamer": {
      "Name": "DLGamer",
      "Enabled": true
    },
    "epic": {
      "Name": "Epic Game Store",
      "Enabled": true
    },
    "fireflower": {
      "Name": "FireFlower",
      "Enabled": true
    },
    "game2": {
      "Name": "2game",
      "Enabled": true
    },
    "gamebillet": {
      "Name": "GameBillet",
      "Enabled": true
    },
    "gamejolt": {
      "Name": "Game Jolt",
      "Enabled": true
    },
    "gamersgate": {
      "Name": "GamersGate",
      "Enabled": true
    },
    "gamesload": {
      "Name": "Gamesload",
      "Enabled": true
    },
    "gamesplanet": {
      "Name": "GamesPlanet UK",
      "Enabled": true
    },
    "gamesplanetde": {
      "Name": "GamesPlanet DE",
      "Enabled": true
    },
    "gamesplanetfr": {
      "Name": "GamesPlanet FR",
      "Enabled": true
    },
    "gamesplanetus": {
      "Name": "GamesPlanet US",
      "Enabled": false
    },
    "gamesrepublic": {
      "Name": "GamesRepublic",
      "Enabled": true
    },
    "gog": {
      "Name": "GOG",
      "Enabled": true
    },
    "greenmangaming": {
      "Name": "GreenManGaming",
      "Enabled": true
    },
    "humblestore": {
      "Name": "Humble Store",
      "Enabled": true
    },
    "humblewidgets": {
      "Name": "Humble Widgets",
      "Enabled": false
    },
    "indiegalastore": {
      "Name": "IndieGala Store",
      "Enabled": true
    },
    "itchio": {
      "Name": "Itch.io",
      "Enabled": true
    },
    "joybuggy": {
      "Name": "JoyBuggy",
      "Enabled": false
    },
    "macgamestore": {
      "Name": "MacGameStore",
      "Enabled": true
    },
    "microsoft": {
      "Name": "Microsoft Store",
      "Enabled": true
    },
    "origin": {
      "Name": "Origin",
      "Enabled": true
    },
    "squenix": {
      "Name": "Square Enix",
      "Enabled": true
    },
    "steam": {
      "Name": "Steam",
      "Enabled": true
    },
    "uplay": {
      "Name": "Uplay",
      "Enabled": true
    },
    "voidu": {
      "Name": "Voidu",
      "Enabled": true
    },
    "wingamestore": {
      "Name": "WinGameStore",
      "Enabled": true
    }
  },
  "EnableGlassEffect": false,
  "OuterBorderThickness": 12,
  "EnableFilterSubSources": true,
  "EnableGlobalHotkey": true,
  "PreferCoverArt": true
}
```

**Comment by felixkmh** [comment]
Can you try it again by installing [felixkmh_QuickSearch_Plugin_2_1_0.zip](https://github.com/felixkmh/QuickSearch-for-Playnite/files/7143816/felixkmh_QuickSearch_Plugin_2_1_0.zip)? If it doesn't work, let me see the log again.

**Comment by savvasdalkitsis** [comment]
The zipped versions works without a crash on all scenarios (with or without glass effect, both local and global) 👍

**Comment by felixkmh** [comment]
Huh, I'm rather surprised that worked xD Must be some weird WPF thing. Anyway, I'm glad it is fixed.
